name: CI/CD Pipeline Frontend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: benjabarrera
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen (Build & Push)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: benjabarrera/ep2-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en EC2 por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Descargar la imagen actualizada
            docker pll benjabarrera/ep2-frontend:latest
            
            # Detener y borrar contenedor antiguo
            docker stop frontend || true
            docker rm frontend || true
            
            # Ejecutar el nuevo contenedor mapeando puerto 80 (Host) a 8080 (Contenedor)
            docker run -d --name frontend -p 80:8080 benjabarrera/ep2-frontend:latest
